#include <vector>
#include <string>
#include <map>
#include <stdexcept>
#include <format>
#include <cstring>
#include <sys/socket.h>
#include <netdb.h>
#include <unistd.h>
#include <deque>
#include <poll.h>
#include <fcntl.h>

#include "command-executor/CommandExecutor.hpp"
#include "constants.hpp"
#include "entry/Entry.hpp"
#include "hashmap/HMap.hpp"
#include "min-heap/MinHeap.hpp"
#include "queue/Queue.hpp"
#include "request/Request.hpp"
#include "response/Response.hpp"
#include "response/types/NilResponse.hpp"
#include "response/types/StrResponse.hpp"
#include "response/types/IntResponse.hpp"
#include "response/types/ErrResponse.hpp"
#include "response/types/ArrResponse.hpp"
#include "response/types/DblResponse.hpp"
#include "thread-pool/ThreadPool.hpp"
#include "utils/buf_utils.hpp"
#include "utils/intrusive_data_structure_utils.hpp"
#include "utils/hash_utils.hpp"
#include "utils/net_utils.hpp"
#include "utils/log.hpp"
#include "utils/time_utils.hpp"

/* Client connection to the server */
struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    Buffer incoming = Buffer();  // data to be parsed by the application
    Buffer outgoing = Buffer();  // responses generated by the application
    // timers
    IdleTimer idle_timer; // if expiry time reached, connection has been idle for too long
};

HMap kv_store; // key-value store
std::vector<Conn *> fd_to_conn; // map of all client connections, indexed by fd
std::vector<struct pollfd> pollfds; // array of pollfds for poll()
Queue idle_timers; // idle timers for active connections, timer closest to expiring is at the front of the queue
MinHeap ttl_timers; // ttl timers for entries in the kv store, timer closest to expiring is at the root of the heap
ThreadPool thread_pool(4); // pool of worker threads for executing asynchronous tasks

/**
 * Gets the address info for the machine running this program which can be used in bind().
 * 
 * @return  Pointer to a struct addrinfo on success. Should be freed when no longer in use.
 *          NULL on error.
 */
struct addrinfo *get_my_addr_info() {
    struct addrinfo *res;
    struct addrinfo hints;

    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_UNSPEC;        // IPv4 or IPv6
    hints.ai_socktype = SOCK_STREAM;    // Stream socket
    hints.ai_flags = AI_PASSIVE;        // Returns wildcard address

    if (getaddrinfo(NULL, PORT, &hints, &res) != 0) {
        return NULL;
    }

    return res;
}

/**
 * Starts the server by creating a listener socket bound to a pre-defined port. 
 * 
 * @param res   Pointer to a struct addrinfo containing the addrinfo for the server.
 * 
 * @return  The listener socket on success.
 *          -1 on error.
 */
int start_server(struct addrinfo *res) {
    struct addrinfo *p;
    int listener;
    for (p = res; p != NULL; p = p->ai_next) {
        if ((listener = socket(p->ai_family, p->ai_socktype, p->ai_protocol)) == -1) {
            log("%s", strerror(errno));
            continue;
        }

        int yes = 1;
        setsockopt(listener, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));  // Allows port to be re-used

        if (bind(listener, p->ai_addr, p->ai_addrlen) == -1) {
            log("%s", strerror(errno));
            close(listener);
            continue;
        }

        if (listen(listener, SOMAXCONN) == -1) {
            log("%s", strerror(errno));
            close(listener);
            continue;
        }

        return listener;
    }

    return -1;
}

/**
 * Initializes the pollfds array from the map of open connections (fd_to_conn).
 */
void init_pollfds(int listener) {
    // reset from last event loop
    pollfds.clear();
    
    struct pollfd pfd = {listener, POLLIN, 0};
    pollfds.push_back(pfd);

    for (Conn *conn : fd_to_conn) {
        // conn set to NULL when connection is terminated
        if (conn == NULL) {
            continue;
        }

        pfd = {conn->fd, 0, 0};
        if (conn->want_read) {
            pfd.events |= POLLIN;
        }

        if (conn->want_write) {
            pfd.events |= POLLOUT;
        }

        pollfds.push_back(pfd);
    }
}

/**
 * Gets the time until the next timer expires.
 * 
 * @return  The time until the next timer expires.
 *          0 if the next timer has already expired.
 *          -1 if there are no active timers.
 */
int32_t get_time_until_timeout() {
    time_t next_timeout_ms = -1;
    time_t now_ms = get_time_ms();

    if (!idle_timers.is_empty()) {
        QNode *node = idle_timers.front();
        IdleTimer *timer = container_of(node, IdleTimer, node);
        next_timeout_ms = timer->expiry_time_ms;
    }

    if (!ttl_timers.is_empty()) {
        MHNode *node = ttl_timers.min();
        TTLTimer *timer = container_of(node, TTLTimer, node);
        if (next_timeout_ms == -1 || timer->expiry_time_ms < next_timeout_ms) {
            next_timeout_ms = timer->expiry_time_ms;
        }
    }

    if (next_timeout_ms == -1) {
        return -1;
    } else if (now_ms >= next_timeout_ms) {
        return 0;
    }

    return next_timeout_ms - now_ms;
}

/** 
 * Sets a socket so that it is non-blocking.
 * 
 * @param fd    The socket to update.
 * 
 * @return  True on success.
 *          False on error.
 */
bool set_non_blocking(int fd) {
    // get current socket flags
    int flags = fcntl(fd, F_GETFL, 0);
    if (flags == -1) {
        return false;
    }

    // Add the O_NONBLOCK flag
    flags |= O_NONBLOCK;

    // update socket flags
    int result = fcntl(fd, F_SETFL, flags);
    if (result == -1) {
        return false;
    }

    return true;
}

/**
 * Handles a new connection on the listener socket.
 * 
 * @param listener  The listener socket.
 */
void handle_new_connection(int listener) {
    int client = accept(listener, NULL, NULL);
    if (client == -1) {
        log("failed to accept new connection");
        return;
    }

    if (!set_non_blocking(client)) {
        log("failed to set socket to non-blocking");
        close(client);
        return;
    }

    Conn *conn = new Conn();
    conn->fd = client;
    conn->want_read = true;

    if (fd_to_conn.size() < (uint32_t) conn->fd) {
        fd_to_conn.resize(conn->fd + 1);
    }

    fd_to_conn[conn->fd] = conn;
    idle_timers.push(&conn->idle_timer.node);

    log("new connection %d", client);
}

/**
 * Resets the expiry time of an idle timer.
 * 
 * Since its expiry time is reset, the timer is also moved to the end of the idle timer queue as it will now expire the 
 * latest.
 * 
 * @param timer The timer to reset.
 */
void reset_idle_timer(IdleTimer *timer) {
    timer->reset();
    idle_timers.remove(&timer->node);
    idle_timers.push(&timer->node);
}

/**
 * Receives data from the connection and stores it in the connection's input buffer.
 * 
 * @param conn  The connection to receive data from.
 * 
 * @return  True on success.
 *          False on error.
 */
bool recv_data(Conn *conn) {
    char buf[64 * 1024]; // 64 KB, large size is to handle pipelined requests
    int recvd = recv(conn->fd, buf, sizeof(buf), 0);
    if (recvd == -1 && errno == EAGAIN) {
        log("connection %d not actually ready to receive", conn->fd);
        return false;
    } else if (recvd < 0) {
        log("unexpected error when receiving data for connection %d", conn->fd);
        return false;
    } else if (recvd == 0) {
        if (conn->incoming.size() == 0) {
            log("peer terminated connection %d", conn->fd);
        } else {
            log("peer terminated connection %d unexpectedly", conn->fd);
        }
        conn->want_close = true;
        return false;
    }

    conn->incoming.append(buf, (uint32_t) recvd);

    return true;
}

/**
 * Tries to parse a request from the connection’s input buffer. Removes the request from the buffer if it is able to 
 * parse one.
 * 
 * @param conn  The connection to parse the request from.
 * 
 * @return  Pointer to the Request on success.
 *          NULL if request cannot be parsed.
 */
Request *parse_request(Conn *conn) {
    auto [request, status] = Request::unmarshal(conn->incoming.data(), conn->incoming.size());

    if (status == Request::UnmarshalStatus::INCOMPLETE_REQ) {
        return NULL;
    } else if (status == Request::UnmarshalStatus::REQ_TOO_BIG) {
        log("request in connection %d's buffer exceeds the size limit", conn->fd);
        conn->want_close = true;
        return NULL;
    }

    conn->incoming.consume(Request::HEADER_SIZE + (*request)->length());

    return (*request);
}

/**
 * Handles when data is ready to be sent on the connection.
 * 
 * @param conn  The connection to send data over.
 */
void handle_send(Conn *conn) {
    int sent = send(conn->fd, conn->outgoing.data(), conn->outgoing.size(), 0);
    if (sent == -1 && errno == EAGAIN) {
        log("connection %d not actually ready to send", conn->fd);
        return;
    } else if (sent < 0) {
        log("unexpected error when sending on connection %d", conn->fd);
        conn->want_close = true;
        return;
    } 

    conn->outgoing.consume((uint32_t) sent);

    if (conn->outgoing.size() == 0) {
        // nothing left to send for connection, change state from write to read 
        conn->want_read = true;
        conn->want_write = false;
    }
}

/**
 * Handles when data is ready to be received on the connection.
 * 
 * @param conn  The connection with data ready to be received.
 */
void handle_recv(Conn *conn) {
    if (!recv_data(conn)) {
        return;
    }

    CommandExecutor cmd_executor(&kv_store, &ttl_timers, &thread_pool);
    while (Request *request = parse_request(conn)) {
        log("request from connection %d: %s", conn->fd, request->to_string().data());

        std::unique_ptr<Response> response = cmd_executor.execute(request->get_cmd());
        if (response->marshal(conn->outgoing) == Response::MarshalStatus::RES_TOO_BIG) {
            log("response to connection %d exceeds the size limit", conn->fd);

            ErrResponse err(ErrResponse::ErrorCode::ERR_TOO_BIG, "response is too big");
            err.marshal(conn->outgoing);
            conn->want_close = true;

            return;
        }

        delete request;
    }

    if (conn->outgoing.size() > 0) {
        // something to send for connection, change state from read to write
        conn->want_read = false;
        conn->want_write = true;
        handle_send(conn); // The socket is likely ready to write in a request-response protocol, try to write it 
                           // without waiting for the next iteration
    }
}

/**
 * Handles when the connection should be closed.
 * 
 * @param conn  The connection to close.
 */
void handle_close(Conn *conn) {
    int fd = conn->fd;

    close(conn->fd);
    fd_to_conn[conn->fd] = NULL;
    idle_timers.remove(&conn->idle_timer.node);
    delete conn;

    log("closed connection %d", fd);
}

/**
 * Checks the idle and TTL timers to see if any have expired.
 * 
 * If a timer has expired, the associated connection/entry is removed.
 */
void process_timers() {
    time_t now_ms = get_time_ms();
    while (!idle_timers.is_empty()) {
        QNode *node = idle_timers.front();
        IdleTimer *timer = container_of(node, IdleTimer, node);
        if (timer->expiry_time_ms > now_ms) {
            break;
        }
        Conn *conn = container_of(timer, Conn, idle_timer);
        log("connection %d exceeded idle timeout", conn->fd);
        handle_close(conn);
    }

    const uint32_t MAX_EXPIRATIONS = 1000;
    uint32_t count = 0;
    while (!ttl_timers.is_empty() && count < MAX_EXPIRATIONS) {
        MHNode *node = ttl_timers.min();
        TTLTimer *timer = container_of(node, TTLTimer, node);
        if (timer->expiry_time_ms > now_ms) {
            break;
        }
        Entry *entry = container_of(timer, Entry, ttl_timer);
        log("key \'%s\' expired", entry->key.data());
        kv_store.remove(&entry->node, are_entries_equal);
        delete_entry(entry, &ttl_timers, &thread_pool);
        count++;
    }
}

int main() {
    struct addrinfo *res = get_my_addr_info();
    if (res == NULL) {
        fatal("failed to get server's addrinfo");
    }

    int listener;
    if ((listener = start_server(res)) == -1) {
        fatal("failed to start server");
    }
    freeaddrinfo(res);

    log("started server");

    while (true) {
        init_pollfds(listener);

        if (poll(pollfds.data(), pollfds.size(), get_time_until_timeout()) == -1) {
            fatal("failed to poll");
        }

        // listener socket always at index 0 of pollfds
        if (pollfds[0].revents & POLLIN) {
            handle_new_connection(listener);
        }

        for (uint32_t i = 1; i < pollfds.size(); i++) {
            uint16_t revents = pollfds[i].revents;
            if (revents == 0) {
                continue;
            }
    
            Conn *conn = fd_to_conn[pollfds[i].fd];
            reset_idle_timer(&conn->idle_timer);

            if (revents & POLLIN) {
                handle_recv(conn);
            }

            if (revents & POLLOUT) {
                handle_send(conn);
            }

            if (revents & POLLERR || conn->want_close) {
                handle_close(conn);
            }
        }

        process_timers();
    }
}
