#include "../buffer/Buffer.hpp"
#include "../request/Request.hpp"
#include "../timers/IdleTimer.hpp"

/* Client connection to the server */
class Conn {
    public:
        int fd = -1; // socket file descriptor

        // application's intention, for the event loop
        bool want_read = false;
        bool want_write = false;
        bool want_close = false;

        // buffered input and output
        Buffer incoming = Buffer();  // data to be parsed by the application
        Buffer outgoing = Buffer();  // responses generated by the application

        // timers
        IdleTimer idle_timer; // if expiry time reached, connection has been idle for too long

        Conn(int fd, bool want_read, bool want_write, bool want_close) : fd(fd), want_read(want_read), want_write(want_write), want_close(want_close) {};
               
        /**
         * Handles when data is ready to be sent over the connection. 
         * 
         * Writes data in the outgoing buffer to the socket and switches the connection's preference to "read" if there
         * is no more data in the outgoing buffer.
         */
        void handle_send();

        /**
         * Handles when data is ready to be received on the connection.
         * 
         * Receives data on the socket, saving it to the incoming buffer. If a request can be parsed from the incoming
         * buffer, exceutes the command contained in the request. Lastly, switches the connection's preference to 
         * "write" if there is data in the outgoing buffer.
         * 
         * @param kv_store      Reference to the kv store.
         * @param ttl_timers    Reference to the TTL timers for entries in the kv store.
         * @param thread_pool   Reference to the thread pool used for asynchronous work.
         */
        void handle_recv(HMap &kv_store, MinHeap &ttl_timers, ThreadPool &thread_pool);

        /**
         * Handles when the connection should be closed.
         * 
         * Removes the idle timer for the connection and the connection itself from the map of all active connections.
         * 
         * @param fd_to_conn    Reference to the map of all active connections, indexed by fd.
         * @param idle_timers   Reference to the idle timers for active connections.
         */
        void handle_close(std::vector<Conn *> &fd_to_conn, Queue &idle_timers);
    private:
        /**
         * Receives data over the connection and stores it in the input buffer.
         * 
         * @return  True on success.
         *          False on error.
         */
        bool recv_data();

        /**
         * Tries to parse a request from the input buffer, removing it from the buffer afterwards.
         * 
         * @return  Pointer to the Request on success.
         *          NULL if request cannot be parsed.
         */
        Request *parse_request();
};
